language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-30.0.3
  - android-30
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

if: tag IS present
stages:
  - name: deploy
    if: branch = master
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- ./gradlew :app:assembleRelease

before_install:
- gem install fir-cli
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- yes | sdkmanager --update
- yes | sdkmanager "platforms;android-30"
- openssl aes-256-cbc -K $encrypted_639db8c6f794_key -iv $encrypted_639db8c6f794_iv
  -in cxz.jks.enc -out cxz.jks -d

deploy:
  provider: releases
  api_key:
    secure: p5oW5PgnkJmOATszLfNe77M9WAXj6vCWjnuh/YhDu9ce8rIVcxuts91jvFEXhXswRJpri52vds3CHTG+W4RaPfetCF4P4mIiyYp0GSkVhhIOqMVLqTiwZZ/5jAx4qVwyMwqPMWOyT2QmyVUD0tnKkMcuV9WZDhNvR5YE5WDeFAn4FuT/CWzljmhR1bwhiEGXQT0t7z2aV8NA/xvt2huvk79+x0E80mdHQlXaVxRfB5BYkHg+l7QmBAva4lgdIq5yeaJlfuqVppMaWvLbJZnA4DkPveiznA4M+2a4B0pXAyN9PRqI6ZLHopmNBGrLblva5XK5mQl5xuJ2LHYJZppzZ2ItRmCZCAhSMLB0YyqfBI80bUfBER1wWl+C21dqjhlt7jg/ykFL8yll7IPJZc+YVQUMbgz4ua87nu+WBzXfzceSw9wkCmM/193lB5TUODjUo9EZfE+u7+AzYKKSAKOvGjsK+/biH4AIpxbC1lHOy86P8QfEDgJY8YVCgWHcXZUogKKqL1pu6JDGcvJv/RU9ocqVIZBj6/CcjtZP12xJ8hKiWlWr1oPMCRzuNUjfWWk65HoC2BbiwQffM1j4YLa8BfZc3EVaXnY/tMbrPuotsGmrPBENS8wzEDJk3UdOMkl+iTAInJPrayWoV6yqQdnD3+j+gsFlmnDEBoGbR0wXmtw=
  file: app/build/outputs/apk/release/app-release.apk
  on:
    repo: iceCola7/TravisDemo
    tags: true
    all_branches: true

after_deploy:
- fir p app/build/outputs/apk/release/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
